name: chat_me
description: A new Flutter chat application using firebase.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/


